services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      KEYCLOAK_APP_HOSTNAME: ${KEYCLOAK_APP_HOSTNAME}
      KEYCLOAK_APP_HOST: ${KEYCLOAK_APP_HOST}
      FIREFLY_APP_HOSTNAME: ${FIREFLY_APP_HOSTNAME}
      FIREFLY_APP_HOST: ${FIREFLY_APP_HOST}
      WEKAN_APP_HOSTNAME: ${WEKAN_APP_HOSTNAME}
      WEKAN_APP_HOST: ${WEKAN_APP_HOST}
      SOCKS5H_HOST: ${CADDY_OUTPUT_SOCKS5H_HOST:-}
      SOCKS5H_PORT: ${CADDY_OUTPUT_SOCKS5H_PORT:-}
      SOCKS5H_USER: ${CADDY_OUTPUT_SOCKS5H_USER:-}
      SOCKS5H_PASSWORD: ${CADDY_OUTPUT_SOCKS5H_PASSWORD:-}

    volumes:
      - ./vol/caddy/data:/data
      - ./vol/caddy/config:/config

    networks:
      - caddy-universe
      - caddy-private
      - caddy-keycloak
      - caddy-firefly
      - caddy-wekan

  caddy-socat-frp:
    image: ghcr.io/ldev1281/docker-socat-socks5h:latest
    container_name: caddy-socat-frp
    restart: unless-stopped

    depends_on:
      - caddy

    environment:
      LISTEN_PORT: ${FRP_PORT}
      TARGET_HOST: ${FRP_HOST}
      TARGET_PORT: ${FRP_PORT}

    networks:
      - caddy-universe
      - caddy-private

  caddy-frp-client:
    image: ghcr.io/ldev1281/docker-frp:latest
    container_name: caddy-frp-client
    restart: unless-stopped

    depends_on:
      - caddy-socat-frp

    environment:
      - FRP_HOST=caddy-socat-frp
      - FRP_PORT=${FRP_PORT}
      - FRP_TOKEN=${FRP_TOKEN}

    networks:
      - caddy-private

networks:
  caddy-universe:
    name: caddy-universe
    driver: bridge

  caddy-private:
    name: caddy-private
    driver: bridge
    internal: true

  caddy-keycloak:
    name: caddy-keycloak
    external: true

  caddy-firefly:
    name: caddy-firefly
    external: true

  caddy-wekan:
    name: caddy-wekan
    external: true
