services:
  caddy:
    image: caddy:latest
    entrypoint: ["/usr/local/bin/caddy-entrypoint.sh"]
    container_name: caddy
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    environment:
      - KEYCLOAK_APP_HOSTNAME
      - KEYCLOAK_APP_HOST
      - KEYCLOAK_APP_HTTP_PORT
      - KEYCLOAK_APP_HTTPS_PORT
      - OUTLINE_APP_HOSTNAME
      - OUTLINE_APP_HOST
      - OUTLINE_APP_PORT

    volumes:
      - ./usr/local/bin/caddy-entrypoint.sh:/usr/local/bin/caddy-entrypoint.sh:ro
      - ./vol/caddy/data:/data
      - ./vol/caddy/config:/config

    networks:
      - caddy-universe
      - caddy-outline
      - caddy-frp
      - caddy-keycloak

  frp-client:
    image: ghcr.io/ldev1281/docker-frp:latest
    container_name: frp-client
    restart: unless-stopped

    depends_on:
      - caddy

    environment:
      FRP_HOST: ${FRP_HOST}
      FRP_PORT: ${FRP_PORT}
      FRP_TOKEN: ${FRP_TOKEN}

    networks:
      - frp-universe
      - caddy-frp

networks:
  caddy-universe:
    name: caddy-universe
    driver: bridge

  caddy-outline:
    name: caddy-outline
    external: true

  caddy-frp:
    name: caddy-frp
    external: true

  caddy-keycloak:
    name: caddy-keycloak
    external: true

  frp-universe:
    name: frp-universe
    driver: bridge
