services:
  
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always

    ports:
      - "80:80"
      - "443:443"

    volumes:
      #
      - ./vol/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      #
      - ./vol/caddy/data:/data
      - ./vol/caddy/config:/config

    networks:
      - caddy-universe
      - caddy-outline
      - caddy-frp

  frp-client:
    image: ghcr.io/ldev1281/docker-frp:latest
    container_name: frp-client
    restart: unless-stopped

    environment:
      FRP_HOST: ${FRP_HOST}
      FRP_PORT: ${FRP_PORT}
      FRP_TOKEN: ${FRP_TOKEN}

    networks:
      - frp-universe
      - caddy-frp



networks:

  caddy-universe:
    name: caddy-universe
    driver: bridge

  caddy-outline:
    name: caddy-outline
    external: true

  caddy-frp:
    name: caddy-frp
    external: true

  frp-universe:
    name: frp-universe
    driver: bridge